### ISSUE TITLE
About the clustering algorithm

### ISSUE THREAD

**Issue by HalvesChen** [zadaianchuk/comus#1]
Hi, thanks for the nice work！
Have you done experiments comparing kmeans clustering and spectral clustering? I am interested in this and hope you can reply me :)

**Comment by zadaianchuk** [comment]
Hi! Yes, we have looked into the performance of 4 different clustering methods, including kmeans 
(See Figure 6: (a) in Appendix. COMUS (Iteration 1) performance with different clustering methods.) 

https://arxiv.org/pdf/2207.05027.pdf

Also, in the ablation studies, we are also including kmeans (No Laplacian Eigenmap is traditional  kmeans)

Hope this helps!
